bitey/users/models.py
from bitey import login_manager, db
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), unique=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(200))
    full_name = db.Column(db.String(100), nullable=True)
    country = db.Column(db.String(60))
    city = db.Column(db.String(100))
    address = db.Column(db.String(100))
    activated = db.Column(db.Boolean, default=False)
    activated_on = db.Column(db.DateTime, default=None)
    created_on = db.Column(db.DateTime, default=datetime.now())


    def __init__(self, username, email, password, country, city, address, full_name=None, activated=False,
                 activated_on=None, created_on=datetime.now()):
        self.username = username
        self.email = email
        self.password = password
        self.full_name = full_name
        self.country = country
        self.city = city
        self.address = address
        self.activated = activated
        self.activated_on = activated_on
        self.created_on = created_on


    def __repr__(self):
        return f'User({self.id}, {self.username})'

bitey/users/forms.py
from bitey import bcrypt
from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import StringField, SelectField, TextAreaField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Optional, Length, DataRequired, Email, EqualTo, ValidationError
from .models import User
from .utils import parse_countries


class SignUpForm(FlaskForm):
    full_name = StringField('Full Name', validators=[Optional(), Length(min=2, max=100)])
    country = SelectField('Country', validators=[DataRequired()], choices=parse_countries(), validate_choice=False)
    city = StringField('City', validators=[DataRequired(), Length(min=2, max=100)])
    address = TextAreaField('Address', validators=[DataRequired(), Length(min=8, max=100)])
    username = StringField('Username', validators=[DataRequired(), Length(min=5, max=30)])
    email = StringField('E-mail', validators=[DataRequired(), Email(), Length(max=100)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=8, max=200)])
    repeat_password = PasswordField('Repeat Password', validators=[EqualTo('password')])
    submit = SubmitField('Sign Up')


    def validate_country(self, field):
        if (field.data, field.data) not in parse_countries():
            raise ValidationError('Country does not exist!')


    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('This username is already taken! Please try using a different one.')


    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('This e-mail is already taken! Please try using a different one.')


class LogInForm(FlaskForm):
    username_or_email = StringField('Username or E-mail', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Log In')


class EditUserForm(FlaskForm):
    full_name = StringField('Full Name', validators=[Optional(), Length(min=2, max=100)])
    country = SelectField('Country', validators=[DataRequired()], choices=parse_countries(), validate_choice=False)
    city = StringField('City', validators=[DataRequired(), Length(min=2, max=100)])
    address = TextAreaField('Address', validators=[DataRequired(), Length(min=8, max=100)])
    username = StringField('Username', validators=[DataRequired(), Length(min=5, max=30)])
    email = StringField('E-mail', validators=[DataRequired(), Email(), Length(max=100)])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Save')


    def validate_country(self, field):
        if (field.data, field.data) not in parse_countries():
            raise ValidationError('Country does not exist!')


    def validate_username(self, field):
        if current_user.username != field.data and User.query.filter_by(username=field.data).first():
            raise ValidationError('This username is already taken! Please try using a different one.')


    def validate_email(self, field):
        if current_user.email != field.data and User.query.filter_by(email=field.data).first():
            raise ValidationError('This e-mail is already taken! Please try using a different one.')


    def validate_password(self, field):
        if not bcrypt.check_password_hash(current_user.password, field.data):
            raise ValidationError('The password is incorrect!')


class ChangePasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired(), Length(min=8, max=200)])
    repeat_password = PasswordField('Repeat Password', validators=[EqualTo('password')])
    submit = SubmitField('Confirm')


class ResetPasswordForm(FlaskForm):
    email = StringField('E-mail', validators=[DataRequired(), Email(), Length(max=100)])
    submit = SubmitField('Reset')


    def validate_email(self, field):
        if not User.query.filter_by(email=field.data).first():
            raise ValidationError('Could not find a user with this e-mail! Please try using a different one.')

bitey/users/views.py
from bitey import db, bcrypt
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime
from .forms import SignUpForm, LogInForm, EditUserForm, ChangePasswordForm, ResetPasswordForm
from .models import User
from .decorators import is_anonymous, is_activated, is_not_activated
from .utils import validate_token, send_activation_email, send_password_change_request_email, remove_whitespaces


users = Blueprint('users', __name__)


@users.route('/signup', methods=('GET', 'POST'))
@is_anonymous('main.home')
def signup():
    form = SignUpForm()

    if form.validate_on_submit():
        password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        user = User(remove_whitespaces(form.username.data), remove_whitespaces(form.email.data), password,
                    remove_whitespaces(form.country.data), remove_whitespaces(form.city.data),
                    remove_whitespaces(form.address.data), remove_whitespaces(form.full_name.data))


        if send_activation_email(user, 'Activate Your Account', 'Thank you for signing up. Please follow link below to '
                                                                'activate your account:'):
            flash('We have sent you an e-mail! Check your inbox to activate your account!', 'info')
        else:
            flash('Could not send an activation e-mail!', 'danger')

        db.session.add(user)
        db.session.commit()

        login_user(user)

        return redirect(url_for('main.home'))

    return render_template('users/signup.html', title='Sign up', form=form)


@users.route('/login', methods=('GET', 'POST'))
@is_anonymous('main.home')
def login():
    form = LogInForm()

    if form.validate_on_submit():
        def validate_and_login(user_object):
            if bcrypt.check_password_hash(user_object.password, form.password.data):
                login_user(user_object)

                return True
            else:
                flash('The password you entered is incorrect!', 'danger')

                return False

        if user := User.query.filter_by(username=form.username_or_email.data).first():
            if validate_and_login(user):
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
        elif user := User.query.filter_by(email=form.username_or_email.data).first():
            if validate_and_login(user):
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('User not found! Please try different credentials.', 'danger')

    return render_template('users/login.html', title='Log in', form=form)


@users.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()

    return redirect(url_for('main.home'))


@users.route('/password/reset', methods=('GET', 'POST'))
@is_anonymous('main.home')
def password_reset():
    form = ResetPasswordForm()

    if form.validate_on_submit():
        if send_password_change_request_email(User.query.filter_by(email=form.email.data).first()):
            flash('We have sent you an e-mail! Check your inbox to reset your password!', 'info')

            return redirect(url_for('users.login'))
        else:
            flash('Could not send a reset password e-mail!', 'danger')

    return render_template('users/password-reset.html', title='Reset Password', form=form)


@users.route('/activation/<token>')
def activation(token):
    if email := validate_token(token):
        if user := User.query.filter_by(email=email).first():
            if user.activated:
                flash('Your account is already activated.', 'info')
            else:
                user.activated = True
                user.activated_on = datetime.now()

                db.session.commit()

                flash('Your account has been activated! Thank you!', 'success')
        else:
            flash('User not found!', 'danger')
    else:
        flash('Token is invalid or has expired!', 'danger')

    return redirect(url_for('main.home'))


@users.route('/profile')
@login_required
def profile():
    return render_template('users/profile.html', title='Profile')


@users.route('/profile/edit', methods=('GET', 'POST'))
@login_required
@is_activated('users.profile')
def edit():
    form = EditUserForm()

    if request.method == 'GET':
        form.full_name.data = current_user.full_name
        form.country.data = current_user.country
        form.city.data = current_user.city
        form.address.data = current_user.address
        form.username.data = current_user.username
        form.email.data = current_user.email

    if form.validate_on_submit():
        current_user.full_name = remove_whitespaces(form.full_name.data)
        current_user.country = remove_whitespaces(form.country.data)
        current_user.city = remove_whitespaces(form.city.data)
        current_user.address = remove_whitespaces(form.address.data)
        current_user.username = remove_whitespaces(form.username.data)
        if form.email.data != current_user.email:
            current_user.email = remove_whitespaces(form.email.data)
            current_user.activated = False

            db.session.commit()

            if send_activation_email(current_user, 'Activate Your Account', "We've noticed that you have changed your "
                                                                            "e-mail, you will now how to reactivate your "
                                                                            "account. Please follow link below to "
                                                                            "activate your account:"):
                flash('We have sent you an e-mail! Check your inbox to reactivate your account!', 'info')
            else:
                flash('Could not send an activation e-mail!', 'danger')

        else:
            db.session.commit()

            flash('Your profile has been edited successfully!', 'success')

        return redirect(url_for('users.profile'))

    return render_template('users/edit.html', title='Edit', form=form)


@users.route('/profile/password/change/request')
@login_required
@is_activated('users.profile')
def password_change_request():
    if send_password_change_request_email(current_user):
        flash('We have sent you an e-mail! Check your inbox to change your password!', 'info')
    else:
        flash('Could not request password change!', 'danger')

    return redirect(url_for('users.profile'))


@users.route('/profile/password/change/<token>', methods=('GET', 'POST'))
def password_change(token):
    if email := validate_token(token):
        if user := User.query.filter_by(email=email).first():
            form = ChangePasswordForm()

            if form.validate_on_submit():
                user.password = bcrypt.generate_password_hash(form.password.data)

                db.session.commit()

                flash('Your password has been changed!', 'success')

                return redirect(url_for('users.profile'))

            return render_template('users/password-change.html', title='Change Password', form=form)
        else:
            flash('User not found!', 'danger')
    else:
        flash('Token is invalid or has expired!', 'danger')

    return redirect(url_for('users.profile'))


@users.route('/profile/resend')
@login_required
@is_not_activated('users.profile')
def resend():
    # TODO: Add cooldown (?)
    if send_activation_email(current_user, 'Activate Your Account', "We've noticed that you have changed your e-mail, "
                                                                    "you will now how to reactivate your account. Please "
                                                                    "follow link below to activate your account:"):
        flash('We have sent you an e-mail! Check your inbox to activate your account!', 'info')
    else:
        flash('Could not send an activation e-mail!', 'danger')

    return redirect(url_for('users.profile'))


@users.route('/profile/delete', methods=('GET', 'POST'))
@login_required
def delete():
    if request.method == 'POST':
        db.session.delete(current_user)
        db.session.commit()

        flash('Your account has been successfully deleted.', 'success')

        return redirect(url_for('main.home'))

    return render_template('users/delete.html', title='Delete Account')

bitey/templates/users/delete.html
{% extends 'base.html' %}
{% block content %}
    <h2>Delete Account</h2>
    <p>Your account will be permanently deleted. This process is not reversible, are you sure you want to continue?</p>
    <form action="" method="post">
        <a class="btn btn-dark" href="{{ url_for('users.profile') }}">No</a>
        <button type="submit" class="btn btn-outline-danger">Yes</button>
    </form>
{% endblock %}

bitey/templates/users/edit.html
{% extends 'base.html' %}
{% block content %}
    <h2>Edit</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.full_name.label(class="form-control-label") }}
            {% if form.full_name.errors %}
                {{ form.full_name(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.full_name.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.full_name(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.country.label(class="form-control-label") }}
            {% if form.country.errors %}
                {{ form.country(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.country.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.country(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.city.label(class="form-control-label") }}
            {% if form.city.errors %}
                {{ form.city(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.city.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.city(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.address.label(class="form-control-label") }}
            {% if form.address.errors %}
                {{ form.address(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.address.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.address(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark") }}
            <a class="btn btn-outline-danger" href="{{ url_for('users.profile') }}">Cancel</a>
        </div>
    </form>
{% endblock %}

bitey/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
    <h2>Log In</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.username_or_email.label(class="form-control-label") }}
            {% if form.username_or_email.errors %}
                {{ form.username_or_email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username_or_email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.username_or_email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
            <a href="{{ url_for('users.password_reset') }}"><small>Forgot Password?</small></a>
        </div>
        <div class="form-group">
            {{ form.remember_me }}
            {{ form.remember_me.label }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-dark") }}
        </div>
    </form>
    <div class="border-top mt-2">
        <small class="text-muted">
            Don't have an account? <a class="ml-2" href="{{ url_for('users.signup') }}">Sign Up</a>
        </small>
    </div>
{% endblock %}

bitey/templates/users/password-change.html
{% extends 'base.html' %}
{% block content %}
    <h2>Change Password</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.repeat_password.label(class="form-control-label") }}
            {% if form.repeat_password.errors %}
                {{ form.repeat_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.repeat_password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.repeat_password(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark") }}
            <a class="btn btn-outline-danger" href="{{ url_for('users.profile') }}">Cancel</a>
        </div>
    </form>
{% endblock %}

bitey/templates/users/password-reset.html
{% extends 'base.html' %}
{% block content %}
    <h2>Reset Password</h2>
    <p>We will send you an e-mail with instructions on how to reset your password.</p>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark") }}
            <a class="btn btn-outline-danger" href="{{ url_for('users.profile') }}">Cancel</a>
        </div>
    </form>
{% endblock %}

bitey/templates/users/profile.html
{% extends 'base.html' %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <h2>{{ current_user.username }}'s Profile</h2>
            {% if current_user.full_name %}
                <h5>{{ current_user.full_name }}</h5>
            {% endif %}
            <hr>
            <p><b>E-mail:</b> {{ current_user.email }}</p>
            <p><b>Country:</b> {{ current_user.country }}</p>
            <p><b>City:</b> {{ current_user.city }}</p>
            <p><b>Address:</b> {{ current_user.address }}</p>
            {% if current_user.activated %}
                <a class="btn btn-outline-dark" href="{{ url_for('users.edit') }}">Edit</a>
                <a class="btn btn-outline-dark" href="{{ url_for('users.password_change_request') }}">Change Password</a>
            {% else %}
                <a class="btn btn-outline-primary" href="{{ url_for('users.resend') }}">Resend Activation E-mail</a>
            {% endif %}
            <a class="btn btn-outline-danger" href="{{ url_for('users.delete') }}">Delete</a>
        </div>
    </div>
{% endblock %}

bitey/templates/users/reset-password.html
{% extends 'base.html' %}
{% block content %}
    <h2>Reset Password</h2>
    <p>We will send you an e-mail with instructions on how to reset your password.</p>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark") }}
            <a class="btn btn-outline-danger" href="{{ url_for('users.profile') }}">Cancel</a>
        </div>
    </form>
{% endblock %}

bitey/templates/users/signup.html
{% extends 'base.html' %}
{% block content %}
    <h2>Sign Up</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.full_name.label(class="form-control-label") }}
            {% if form.full_name.errors %}
                {{ form.full_name(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.full_name.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.full_name(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.country.label(class="form-control-label") }}
            {% if form.country.errors %}
                {{ form.country(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.country.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.country(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.city.label(class="form-control-label") }}
            {% if form.city.errors %}
                {{ form.city(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.city.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.city(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.address.label(class="form-control-label") }}
            {% if form.address.errors %}
                {{ form.address(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.address.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.address(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.repeat_password.label(class="form-control-label") }}
            {% if form.repeat_password.errors %}
                {{ form.repeat_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.repeat_password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.repeat_password(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-dark") }}
        </div>
    </form>
    <div class="border-top mt-2">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Log In</a>
        </small>
    </div>
{% endblock %}