bitey/main/views.py
from flask import Blueprint, render_template


main = Blueprint('main', __name__)


@main.route('/')
def home():
    return render_template('main/home.html')

bitey/users/views.py
from bitey import db, bcrypt
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime
from .forms import SignUpForm, LogInForm, EditUserForm, ChangePasswordForm, ResetPasswordForm
from .models import User
from .decorators import is_anonymous, is_activated, is_not_activated
from .utils import validate_token, send_activation_email, send_password_change_request_email, remove_whitespaces


users = Blueprint('users', __name__)


@users.route('/signup', methods=('GET', 'POST'))
@is_anonymous('main.home')
def signup():
    form = SignUpForm()

    if form.validate_on_submit():
        password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        user = User(remove_whitespaces(form.username.data), remove_whitespaces(form.email.data), password,
                    remove_whitespaces(form.country.data), remove_whitespaces(form.city.data),
                    remove_whitespaces(form.address.data), remove_whitespaces(form.full_name.data))


        if send_activation_email(user, 'Activate Your Account', 'Thank you for signing up. Please follow link below to '
                                                                'activate your account:'):
            flash('We have sent you an e-mail! Check your inbox to activate your account!', 'info')
        else:
            flash('Could not send an activation e-mail!', 'danger')

        db.session.add(user)
        db.session.commit()

        login_user(user)

        return redirect(url_for('main.home'))

    return render_template('users/signup.html', title='Sign up', form=form)


@users.route('/login', methods=('GET', 'POST'))
@is_anonymous('main.home')
def login():
    form = LogInForm()

    if form.validate_on_submit():
        def validate_and_login(user_object):
            if bcrypt.check_password_hash(user_object.password, form.password.data):
                login_user(user_object)

                return True
            else:
                flash('The password you entered is incorrect!', 'danger')

                return False

        if user := User.query.filter_by(username=form.username_or_email.data).first():
            if validate_and_login(user):
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
        elif user := User.query.filter_by(email=form.username_or_email.data).first():
            if validate_and_login(user):
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('User not found! Please try different credentials.', 'danger')

    return render_template('users/login.html', title='Log in', form=form)


@users.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()

    return redirect(url_for('main.home'))


@users.route('/password/reset', methods=('GET', 'POST'))
@is_anonymous('main.home')
def password_reset():
    form = ResetPasswordForm()

    if form.validate_on_submit():
        if send_password_change_request_email(User.query.filter_by(email=form.email.data).first()):
            flash('We have sent you an e-mail! Check your inbox to reset your password!', 'info')

            return redirect(url_for('users.login'))
        else:
            flash('Could not send a reset password e-mail!', 'danger')

    return render_template('users/password-reset.html', title='Reset Password', form=form)


@users.route('/activation/<token>')
def activation(token):
    if email := validate_token(token):
        if user := User.query.filter_by(email=email).first():
            if user.activated:
                flash('Your account is already activated.', 'info')
            else:
                user.activated = True
                user.activated_on = datetime.now()

                db.session.commit()

                flash('Your account has been activated! Thank you!', 'success')
        else:
            flash('User not found!', 'danger')
    else:
        flash('Token is invalid or has expired!', 'danger')

    return redirect(url_for('main.home'))


@users.route('/profile')
@login_required
def profile():
    return render_template('users/profile.html', title='Profile')


@users.route('/profile/edit', methods=('GET', 'POST'))
@login_required
@is_activated('users.profile')
def edit():
    form = EditUserForm()

    if request.method == 'GET':
        form.full_name.data = current_user.full_name
        form.country.data = current_user.country
        form.city.data = current_user.city
        form.address.data = current_user.address
        form.username.data = current_user.username
        form.email.data = current_user.email

    if form.validate_on_submit():
        current_user.full_name = remove_whitespaces(form.full_name.data)
        current_user.country = remove_whitespaces(form.country.data)
        current_user.city = remove_whitespaces(form.city.data)
        current_user.address = remove_whitespaces(form.address.data)
        current_user.username = remove_whitespaces(form.username.data)
        if form.email.data != current_user.email:
            current_user.email = remove_whitespaces(form.email.data)
            current_user.activated = False

            db.session.commit()

            if send_activation_email(current_user, 'Activate Your Account', "We've noticed that you have changed your "
                                                                            "e-mail, you will now how to reactivate your "
                                                                            "account. Please follow link below to "
                                                                            "activate your account:"):
                flash('We have sent you an e-mail! Check your inbox to reactivate your account!', 'info')
            else:
                flash('Could not send an activation e-mail!', 'danger')

        else:
            db.session.commit()

            flash('Your profile has been edited successfully!', 'success')

        return redirect(url_for('users.profile'))

    return render_template('users/edit.html', title='Edit', form=form)


@users.route('/profile/password/change/request')
@login_required
@is_activated('users.profile')
def password_change_request():
    if send_password_change_request_email(current_user):
        flash('We have sent you an e-mail! Check your inbox to change your password!', 'info')
    else:
        flash('Could not request password change!', 'danger')

    return redirect(url_for('users.profile'))


@users.route('/profile/password/change/<token>', methods=('GET', 'POST'))
def password_change(token):
    if email := validate_token(token):
        if user := User.query.filter_by(email=email).first():
            form = ChangePasswordForm()

            if form.validate_on_submit():
                user.password = bcrypt.generate_password_hash(form.password.data)

                db.session.commit()

                flash('Your password has been changed!', 'success')

                return redirect(url_for('users.profile'))

            return render_template('users/password-change.html', title='Change Password', form=form)
        else:
            flash('User not found!', 'danger')
    else:
        flash('Token is invalid or has expired!', 'danger')

    return redirect(url_for('users.profile'))


@users.route('/profile/resend')
@login_required
@is_not_activated('users.profile')
def resend():
    # TODO: Add cooldown (?)
    if send_activation_email(current_user, 'Activate Your Account', "We've noticed that you have changed your e-mail, "
                                                                    "you will now how to reactivate your account. Please "
                                                                    "follow link below to activate your account:"):
        flash('We have sent you an e-mail! Check your inbox to activate your account!', 'info')
    else:
        flash('Could not send an activation e-mail!', 'danger')

    return redirect(url_for('users.profile'))


@users.route('/profile/delete', methods=('GET', 'POST'))
@login_required
def delete():
    if request.method == 'POST':
        db.session.delete(current_user)
        db.session.commit()

        flash('Your account has been successfully deleted.', 'success')

        return redirect(url_for('main.home'))

    return render_template('users/delete.html', title='Delete Account')

bitey/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/17f4471747.js" crossorigin="anonymous"></script>

    {% if title %}
        <title>Bitey | {{ title }}</title>
    {% else %}
        <title>Bitey</title>
    {% endif %}
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-md navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">
                <img src="{{ url_for('static', filename='logo.png') }}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                Bitey
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('users.profile') }}"><i class="fas fa-user-circle mr-1"></i>Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}"><i class="fas fa-sign-out-alt mr-1"></i>Log Out</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.signup') }}"><i class="fas fa-user-plus mr-1"></i>Sign Up</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}"><i class="fas fa-sign-in-alt mr-1"></i>Log In</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>